In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
may_2020 = "Resources/JC-202005-citibike-tripdata.csv"
jun_2020 = "Resources/JC-202006-citibike-tripdata.csv"
jul_2020 = "Resources/JC-202007-citibike-tripdata.csv"
aug_2020 = "Resources/JC-202008-citibike-tripdata.csv"

In [3]:
may_2020_df = pd.read_csv(may_2020)
jun_2020_df = pd.read_csv(jun_2020)
jul_2020_df = pd.read_csv(jul_2020)
aug_2020_df = pd.read_csv(aug_2020)
aug_2020_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,561,2020-08-01 00:00:16.5960,2020-08-01 00:09:38.5610,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42303,Customer,1994,2
1,236,2020-08-01 00:00:46.3900,2020-08-01 00:04:42.8890,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,44989,Subscriber,1996,1
2,384,2020-08-01 00:02:38.9250,2020-08-01 00:09:03.7590,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,41696,Subscriber,1984,2
3,1302,2020-08-01 00:03:27.0270,2020-08-01 00:25:09.2120,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42310,Customer,1993,1
4,5561,2020-08-01 00:03:57.4810,2020-08-01 01:36:38.5000,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,42346,Customer,1995,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43262,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,Subscriber,1977,1
43263,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,Subscriber,1986,1
43264,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,Subscriber,1960,1
43265,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,Subscriber,1994,1
43266,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,Subscriber,1984,2

In [5]:
combined_CitiBike_df = pd.merge(may_2020_df, jun_2020_df, how='outer')
combined_CitiBike_df2 = pd.merge(combined_CitiBike_df, jun_2020_df, how='outer')
combined_CitiBike_df3 = pd.merge(combined_CitiBike_df2, jul_2020_df, how='outer')
combined_CitiBike_df3 = pd.merge(combined_CitiBike_df3, aug_2020_df, how='outer')

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,349,2020-05-01 00:09:45.5860,2020-05-01 00:15:35.2930,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42581,Customer,1969,0
1,138,2020-05-01 01:11:22.5280,2020-05-01 01:13:41.2460,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42105,Subscriber,1949,1
2,229,2020-05-01 05:31:29.5350,2020-05-01 05:35:19.2400,3483,Montgomery St,40.719420,-74.050990,3186,Grove St PATH,40.719586,-74.043117,42320,Customer,1984,1
3,261,2020-05-01 05:51:39.3960,2020-05-01 05:56:00.9370,3278,Monmouth and 6th,40.725685,-74.048790,3186,Grove St PATH,40.719586,-74.043117,42170,Subscriber,1974,2
4,168,2020-05-01 06:06:31.9510,2020-05-01 06:09:20.1410,3194,McGinley Square,40.725340,-74.067622,3195,Sip Ave,40.730897,-74.063913,42352,Subscriber,1966,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61993,2828,2020-06-30 23:53:19.7380,2020-07-01 00:40:28.5760,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,18351,Customer,1969,0
61994,2729,2020-06-30 23:54:44.0100,2020-07-01 00:40:13.6470,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,44401,Customer,1969,0
61995,2788,2020-06-30 23:54:52.1920,2020-07-01 00:41:20.6500,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42334,Customer,1969,0
61996,2702,2020-06-30 23:56:14.6650,2020-07-01 00:41:16.7820,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42463,Customer,1969,0
61997,2649,2020-06-30 23:57:46.1490,2020-07-01 00:41:55.5060,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42468,Customer,1998,2